version: "3.9"

services:

  app:
    container_name: organizations_handbook
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env.example
    depends_on:
      - db
    networks:
      - bridge


  db:
    container_name: db_organizations
    image: postgis/postgis:16-3.5-alpine
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    env_file:
      - .env.example
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bridge


networks:
  bridge:
    driver: bridge

volumes:
  pgdata: